apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apigee-05-ingress-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  source:
    repoURL: https://github.com/MathewLove17/apigeePoc.git
    targetRevision: HEAD
    path: POC/charts/apigee-ingress-manager
    helm:
      releaseName: apigee-ingress-manager
      valueFiles:
        - ../../runtime/apigee-hybrid/poc/values/ingress-manager.yaml
  destination:
    server: https://clusterapigee-dns-1vt88dy8.hcp.westeurope.azmk8s.io:443
    namespace: apigee
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
